### ISSUE TITLE
`BufCompose` argument `envBuf`

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-core#123]
This was requested at the NOTAM workshop and it is something that I've wanted as well. I would like to have an optional argument to BufCompose that is a buffer containing and envelope shape that will  be applied to source before being copied into destination. This way if one were using BufCompose to add grains to a buffer they could be enveloped properly.

Another possibility is, rather than `envBuf`, a simple attack and decay in frames, however this would not allow for more complex envelope shapes.

Lastly, this could also be a separate object, `FluidBufEnv.processBlocking(s,src,destination,envBuf)`

Thoughts?

This might be a good one for me or someone to dip their toes into the C++ since it's basically buffer reading, writing, and number multiplication...

**Comment by jamesb93** [comment]
I would hesitate to add any of this to FluCoMa and instead educate on the options one has outside of the toolkit. Just feels like feature creep to me more than anything.

**Comment by tedmoore** [comment]
> I would hesitate to add any of this to FluCoMa and instead educate on the options one has outside of the toolkit. Just feels like feature creep to me more than anything.

That's a good point. I don't know of a way to do this natively without some really crummy work arounds. I'll dig in SC and see if I find something. It's definitely a hugely useful thing to have exist.

**Comment by tedmoore** [comment]
I just remembered that @tremblap has this: https://github.com/tremblap/OfflineBufferProcesses so I'm gonna fork it and see if i can implement. Should be straight forward!

**Comment by jamesb93** [comment]
nice! good luck. I think Max buffer stuff is possibly a little more permissive, because you don't have to think about doing it on the server vs lang.

**Comment by tremblap** [comment]
actually

**Comment by tremblap** [comment]
actually I'm reopening this since it was on the bitbucket for 3.5 years and have been requested by many people... I'm not saying it is urgent, nor that the interface is straightforward (where to stop adding feature is a big question) but it is worth keeping in the loop.

**Comment by tedmoore** [comment]
thanks to @tremblap for making it easy to extend his OfflineBufferProcesses. Last night I added a new method to Buffer for doing this:
 
https://github.com/tedmoore/OfflineBufferProcesses/blob/88aac9295ac585fe757027e984597ae90747d86e/OfflineBufferProcesses.cpp#L128

Interface suggestions welcome. It's not documented yet, it's a TODO.

**Comment by jamesb93** [comment]
> actually I'm reopening this since it was on the bitbucket for 3.5 years and have been requested by many people... I'm not saying it is urgent, nor that the interface is straightforward (where to stop adding feature is a big question) but it is worth keeping in the loop.

I think I remember people in the first plenary asking for it! It does add a lot more attributes to the object though so maybe conceiving it as a separate entity would be an interesting approach.

**Comment by weefuzzy** [comment]
My resistance to doing this has historically had a number of dimensions 
1. `BufCompose`'s interface is already too complex
2. As soon as this is implemented it will be followed immediately by follow up feature requests for cases where the modulating waveform is differently sized to the source, and therein lies a quagmire of special cases 
3. All of which tends, inch by inch, to devoting time to making a generic buffer processing framework that, frankly, is not what I'm here for 

Someone is welcome to take a crack at it. The simplest approach would be to just give a choice of operator on `BufCompose` between `+` and `*`. However, this wouldn't leave much room for dealing with the follow up requests, so a fresh object would possibly be better. OTOH, if one is as pessimistic about slippery slopes as I am, a third option would be to just start a new repo geared towards providing a selection of operators on buffers.

**Comment by tremblap** [comment]
we just need to decide a hard line of what this object is for. we are not providing a generic compositing of buffers, but what is needed in fluid corpus manipulation (for instance in KR) - since this was resisted by Owen and Gerard, I have to be honest that I never missed it for real (in realtime) except to do sexy hybrid compositing.

so my idea for now would be to keep that as a low-hanging fruit wishlist. as for hardline, I'd add fadeinlen and fadeoutlen as attributes with 0 as default and that's it. but right away when I spoke about that with other composers, the idea of power vs lin curves crept in... so I agree with @weefuzzy that there is a danger there :)
