### ISSUE TITLE
FluidPCA is not providing the same variance

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-core#137]
The SC UT tests data out of a given dataset, and passes that test and all the other tests of value. The only test that fails in the variance reported between beta6 and now.

This is true in Max and SC

Test code and dataset attached.

beta6:
variance: 0.669702

now:
variance: 0.914936 (with the extra dataset name prepended in SC)

which one is right?

[Archive.zip](https://github.com/flucoma/flucoma-core/files/8619489/Archive.zip)

**Comment by weefuzzy** [comment]
To clarify, both Max and SC report a different variance between beta6 and now, and they both report the same thing? (Because you said they were different on discord...)

**Comment by tremblap** [comment]
Yes - further investigation showed that both are different between now and then, but they agreed between themselves within a version.

**Comment by weefuzzy** [comment]
I think it was wrong before and now it is right, insofar as it agrees with sklearn. Some shitty code 
```python 
from sklearn.decomposition import PCA
import json 
import numpy as np

with  open("/Users/owen/Downloads/Archive 10/testPCAds.json",'r') as f:
    ds = json.load(f)

data = ds['data']

data.get('0')

d = np.zeros((len(data.keys()),len(data.get('0'))))
 
i = 0  
for k,v in data.items(): 
    d[i:] = v    
    i = i + 1

pca = PCA(2)
pca.fit(d)

pca.explained_variance_
pca.explained_variance_ratio_.sum()
```
=> 0.9149359190709427

**Comment by weefuzzy** [comment]
I'm sure there's a much cleverer way of doing that, but whatevs

**Comment by tremblap** [comment]
ok so there was a bug and now it is fixed? If that is the case, then close this and I'll update the value in the UTs

**Comment by weefuzzy** [comment]
Looks that way. From a very quick comparison pre / post whitening commits, before it wasn't working with squares of the singular values to get the explained variance and now it is. So, yes, close and update the tests
