### ISSUE TITLE
MDS: KL Divergence & Cosine Distance look the same

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-core#146]
The last two here look conspicuously the same--which makes me wonder if there's something going wrong under the hood.
<img width="1712" alt="Screenshot 2022-05-26 at 17 56 16" src="https://user-images.githubusercontent.com/1531144/170538633-c785843d-6bbd-4c73-b837-e7f08ae96d5d.png">
<img width="1712" alt="Screenshot 2022-05-26 at 18 01 45" src="https://user-images.githubusercontent.com/1531144/170538641-f925aa50-4dd0-4bb9-9fb7-6407cde9a2c5.png">

**Comment by weefuzzy** [comment]
See my comment on your recent PR: the client enumeration only goes up to KL, so anything you put above that is going to clip (hence they look the same)

**Comment by weefuzzy** [comment]
I guess we could have an issue for sorting out the enum in the client though...
