### ISSUE TITLE
Name of BufNNDSVD object

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-core#157]
In the meeting on `1/06/2022`, we discussed changing this to something else to be more friendly to users.

Ideas were:

`BufNMFPrep` and `BufNMFSeed`.

@g-roma do you have any suggestions for this?

**Comment by weefuzzy** [comment]
BufNMFInitialize ?

**Comment by jamesb93** [comment]
> BufNMFInitialize ?

I don't mind that :)

**Comment by weefuzzy** [comment]
Mind you, it'll be mouthful in lower case.

**Comment by g-roma** [comment]
The problem is there are other ways to initialise NMF, e.g. the default random, or directly from data. The name used here was the name of the algorithm, which was more consistent with the way we named other objects.

**Comment by tremblap** [comment]
I prefer BufNMFSeed for one reason: http://nimfa.biolab.si/nimfa.methods.seeding.nndsvd.html

I also understand that concept having used prng forever 

and it is short :)

**Comment by weefuzzy** [comment]
> The problem is there are other ways to initialise NMF, e.g. the default random, or directly from data. The name used here was the name of the algorithm, which was more consistent with the way we named other objects.

I don't think the first point matters all that much: more ways could be added in the future, and we're under no obligation to be comprehensive  (there's other ways of, e.g. estimating pitch as well, but we still call the object fluid.pitch). The second point has its pros and cons: naming after algorithms avoids being overly prescriptive about what something is for, but at the cost of mystification and, therefore, exclusivity. 

This object, in particular, has been the cause of more nonplussed shrugging than its fair share: NMF is already niche, and this is a niche thing within. As a result, no-one uses it, or really knows that it's there. Given that it has no other obvious application, I think there's a pretty strong case for just calling it something more useful.

**Comment by tremblap** [comment]
I agree with @weefuzzy - I think the reference here is helpful, and we have done a few sideways transgressions for better understanding and usability. the object is incredibly geek, and the search of the nndsvd string will still report the new FluidBufNMFSeed (fluid.bufnmfseed(~)) so specialists will get it. we should also put a note in bufnmf beyond the releated-object-list I think.



> Mind you, it'll be mouthful in lower case.

fluid.bufnmfinitialise (or ze) is indeed long and prone to typos in pd - the poor us without autocomplete ;)

**Comment by tremblap** [comment]
See https://github.com/flucoma/flucoma-core/pull/173
