### ISSUE TITLE
BufNMFCross not setting output buffer properties (and crashing server)

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-core#162]
When this code is run:
```
(
~target = Buffer.readChannel(s,FluidFilesPath("Nicol-LoopE-M.wav"),channels:[0]);
~source = Buffer.readChannel(s,FluidFilesPath("Tremblay-SA-UprightPianoPedalWide.wav"),channels:[0]);
~output = Buffer(s);
)

FluidBufNMFCross.process(s,~target,~source,~output,action:{"done".postln})
//wait for it to be done. It can take a while, depending on the length of your source.
~output.play
```
The last line returns the error:
`ERROR: a PlayBuf: wrong number of channels (nil)`
Which means that the process is not setting the ~output buffer properties like other objects do.

Also, when I change `FluidBufNMFCross.process` to `FluidBufNMFCross.processBlocking` it crashes the server, which deep inside feels related to the previous NNDSVD error that i see @weefuzzy just fixed. Maybe this will fix that too...i'm going to pull and test it all now!

**Comment by weefuzzy** [comment]
There was an issue with the maxFFTSize not being sent but also an issue with crashes when the polyphony was greater than the available rank, fixed by 58b1f5faa014e106ca5ba2025eb8d2267b14399f
