### ISSUE TITLE
More explanation of `Transients` parameters

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-core#166]
I'm hoping that someone can offer a bit more explanation of some of the parameters in `Transients`. I know a few have been digging around in the code recently, so hopefully it can all be off the top of mind.

1. How does `blockSize` get used? How does `order` samples fit inside (get processed within) `blockSize` samples? 
2. I'm assuming that `order` must be less than `blockSize`?
3. Why can a detected transient not be longer than half of `blockSize`? (This is probably related to above?)
4. When `padSize` says it is used to "avoid boundary issues", what does this mean? What is happening within the surrounding pads?
5. `skew` says it ranges from -10 to 10. Are there units for this? Is it dB? (I understand what it's for, just not what the units are) Does the default 0 mean that "peaks" are not modified at all before thresholding?
6. The units for `threshFwd` and `threshBack` are in standard deviations?

Thank you!

**Comment by AlexHarker** [comment]
> Why can a detected transient not be longer than half of blockSize? (This is probably related to above?)

That's not actually quite correct. It can't be more than half the hopSize (I had to check the code):

```
if (count > (hopSize() / 2))
    {
      std::fill(mDetect.data(), mDetect.data() + hopSize(), 0.0);
      count = 0;
    }
```

So that is enforced, but I don't really remember why - intuitively if over half the bit you are dealing with is "error" that seems like something has gone wrong, but the place to look would be the Godsill & Rayner - Digital Audio Restoration book. I assume that I would have done it for some reason outlined there, although I can't promise that is the case.

**Comment by tedmoore** [comment]
> the Godsill & Rayner - Digital Audio Restoration book

I read the chapter. I can't say that I absorbed all of it...

Thanks @weefuzzy and @AlexHarker for your help!

**Comment by weefuzzy** [comment]
Yeah, the book's pretty thin on concrete implementation advice (but frank about it: "We do not detail the precise structure of such an algorithm as most of the ideas are ad hoc"). My best guess for the half hopSize thing is that the interpolation stage might really struggle if it's having to infer more than half the samples in a given block and, as Alex says, if one's error signal is almost all error then presumably something is rotten in Denmark. 

However, I think that this condition could possibly lead to surprising front-end behaviour, in that if the thresholds are too low then presumably nothing will happen. I might experiment with commenting that out and seeing what explodes.
