### ISSUE TITLE
Why is /MT forced on Windows? PyTorch must be /MD which means they can't be used together

### ISSUE THREAD

**Issue by robclouth** [flucoma/flucoma-core#21]
https://github.com/flucoma/flucoma-core/blob/0e85ef4b1d0c40daa0f7354182d713706944a377/CMakeLists.txt#L121

/MT is forced on Windows. This causes issues with PyTorch (in c++) which as of now must be built with /MD.
I've removed that section in the CMakeLists.txt and it builds and runs fine. Why is it in there?

**Comment by weefuzzy** [comment]
Hi @robclouth , 

It's there so we can statically link the MSVC C++ runtime into externals / plugins and not have to distribute a specific version of the runtime DLL, with all the fun and fragility that entails. It's standard procedure for Max externals (and I think we inherited this from their SDK; see this old forum post for what seems to be the birth of this practice: https://cycling74.com/forums/error-126-loading-external/replies/1#reply-58ed21cd43f50b22d4bb958b). 

Bummer that this causes problems with pytorch. Could you tell us a bit about the context you're working in? Are you just using the algorithms as a standalone API, or are you also looking to deploy to Max/SC with our stuff? If the former, then I guess the sensible course of action would be to disaggregate the (simpler) requirements of `core`'s algorithms from the deployment assumptions of the rest of the framework.

**Comment by robclouth** [comment]
That makes a lot of sense, I hadn't considered that. I'm guessing this is why we haven't seen any pytorch stuff in Max/Ableton on windows. It would be a faff to distribute.

I'm working a max external that uses an algorithm written in pytorch for doing audio mosaicing. I'm using flucoma for the mels extraction and onset detection. 

I'll just override or use my fork for now then.

**Comment by robclouth** [comment]
Ah, it's only in debug mode that you can't use /MT with pytorch. Phew!
