### ISSUE TITLE
fluid.ampgate~ cpu usagewith with `minlength` attributes

### ISSUE THREAD

**Issue by weefuzzy** [flucoma/flucoma-core#22]
via https://discourse.flucoma.org/t/fluid-ampgate-cpu-usage/949

Reports of CPU hitting 90-100 % with the `minlength` attributes set in the order of 100 - 1000 ms. Will profile...

**Comment by tremblap** [comment]
Example code below goes from 65% to 0.6% in SC, nice one!

`
b = Buffer.read(s,File.realpath(FluidAmpGate.class.filenameSymbol).dirname.withTrailingSlash ++ "../AudioFiles/Nicol-LoopE-M.wav");

(
{var env, source = PlayBuf.ar(1,b,loop: 1);
    env = FluidAmpGate.ar(source, rampUp:441, rampDown:2205, onThreshold:-27, offThreshold: -31, minSilenceLength:4410, lookBack:441, highPassFreq:20, lookAhead: 22050);
    DelayN.ar(source,delaytime:22050/44100)*env;
}.play;
)
`

**Comment by tremblap** [comment]
I would merge now, but I have sent a compiled version to the bug reporter to see if it works for him.
