### ISSUE TITLE
AmpFeatureClient and AmpSliceClient have dissimilar initialisation values

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-core#221]
This one doesn't cause any badness, but should be rectified.

`AmpFeatureClient` initialiases with a floor of -145 which is outside its specified minimum and maximum range. It Instead should have the same init value as AmpSliceClient, I suppose :)

You can compare the two lines here:

https://github.com/flucoma/flucoma-core/blob/main/include/clients/rt/AmpFeatureClient.hpp#L41
https://github.com/flucoma/flucoma-core/blob/main/include/clients/rt/AmpSliceClient.hpp#L46

**Comment by weefuzzy** [comment]
That must be a sausage fingers thing

**Comment by jamesb93** [comment]
An easy one to sausage fingers indeed and a good first issue!

**Comment by tremblap** [comment]
and a good test of cherry-picking fixes for the main branch

**Comment by tremblap** [comment]
fixed in current pre-prod, should be compiling on that branch
