### ISSUE TITLE
Examples build fails, `AudioFile/IAudioFile.h` is not found

### ISSUE THREAD

**Issue by lewardo** [flucoma/flucoma-core#233]
@AlexHarker 
When compiling in the examples directory the build fails throwing

```fatal  error C1083: Cannot open include file: 'AudioFile/IAudioFile.h': No such file or directory```

from include in `flucoma-core/examples/describe.cpp:16`

![error output](https://github.com/flucoma/flucoma-core/assets/89988886/3502dc4e-95cf-4dcb-a93f-bf69a666eee9)

**Comment by AlexHarker** [comment]
Two main things to check here. 

- I assume that you are pulling in HISSTools_Library via cmake however, you are building (this looks like a visual studio project - is that correct)? Can you find the location of that repo (as far as I can see what gets pulled should have the correct contents).
- As far as I can see the cmake should end up including the HISSTools_Library directory, but I'm just reading from source at the moment (and not checking on a local copy by running cmake)
-

**Comment by AlexHarker** [comment]
How was this closed?

**Comment by tremblap** [comment]
because I was dumb and built from the wrong folder. @lewardo is supposed to have amended the read me...
