### ISSUE TITLE
SineExtraction::init() doesn't reset mBuf

### ISSUE THREAD

**Issue by AlexHarker** [flucoma/flucoma-core#236]
The contents of mBuf should have a consistent size, but if it isn't reset when init() is called this can not be the case (leading to possible crashes or undefined behaviour).

When this object was updated the reset was commented out, but it is needed, so I would propose that:

https://github.com/flucoma/flucoma-core/blob/2681d58fd4642c67a4135a28b7e19b0a5f9d5972/include/algorithms/public/SineExtraction.hpp#L57

Should be:

`   mBuf = makeEmptyQueue(alloc);
`

Doing so solves an eigen_assert I get with debug builds. @weefuzzy ?

**Comment by weefuzzy** [comment]
Yes. Or just call `clear()`? Horses for courses.

**Comment by AlexHarker** [comment]
oh sorry - on mBuf - I don't mind either way but it asserts without something and is liable to crash, so it would be good to fix. @weefuzzy happy to PR whichever you'd prefer.

**Comment by weefuzzy** [comment]
Cool, thanks. Very slight aesthetic preference to calling `clear()`.

**Comment by AlexHarker** [comment]
Turns out that clear() is not a thing for a queue.

**Comment by weefuzzy** [comment]
Well then, that makes our choice.

**Comment by AlexHarker** [comment]
Fixed in 7247a3614b60d8e363f670482ef2aa50d7f61b1c
