### ISSUE TITLE
`fluid.bufampslice~` not working correctly (when using `@numframes`)

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-core#259]
Porting this over here from [the thread I made on the Discourse](https://discourse.flucoma.org/t/fluid-bufampslice-not-working-correctly-when-using-numframes/).

So I’m building [a cascading onset detection thing](https://discourse.flucoma.org/t/chaining-onset-detectors-novelty-ampslice/503/5) using `fluid.bufonsetslice~` followed by `fluid.bufampslice~` and when testing things in context, I’m noticing that `fluid.bufampslice~` is rarely returning valid values when I use the `@numframes` attribute.

In this example if I analyze the whole buffer (`jongly.aif`) I get a bunch of onsets detected (notably not including the first onset), but the moment I add `@numframes 1024` I don’t get any onsets at all anymore. Only when I change `@numframes` to a huge number (`8192`) do I start getting onsets again.

It seems like this is broken to me?

The only thing I can think of is there’s some window being applied when using `@numframes`, but even with that, I would think that adding a `@startframe` offset would compensate for that, but still nothing.

![b167370d3686ff8fa697be85da0b7dd3cf7db232](https://github.com/flucoma/flucoma-max/assets/2747015/044d9ba6-c941-4b64-9c2e-df5e4df80ffe)

```
----------begin_max5_patcher----------
1584.3oc0Y0raaiCD9rySAWgdzUf+JRsW1dbeGVTTHaSYqTYICI53jTz9ruC
IkxOM1wzQRF6lCgfzTb32Lbl4aH+wMyhVTeutMB8mn+AMa1OtY1L2P1Al00e
Vz1r6WVl05lVT09sKzMQy8+DzqnpTab+FoavhUtYVu31OyT8ybWVS1VsQ27M
cU1hRscJ3mWk58l9kg1MpeHyC6z98WTzbTzhrp0Qnu9zhZVtonZ82ZzKM9YI
37X7bDUxrMBrqCMFi9p8S94M2X+27.A6x5sa0UldLXz26jRDOFYZd.spHOW2
.S.AHH2hu1XTcU4CnC0MeuEcnvrAstXcVkoXIzqZU8g1+pe0JKpzKq2W4VRd
OhZzsvBlYJpq91qlAqaF40Ul7rk5WpwWreQmJkDpgII5EqWawitulZUWGylf
ewjq.b5Vm+VWdmFPVVzoMGLpy.fkwBngSr8RwVywq15sEqbqIaDMRrXTUswt
ePG1nq7FlrprxGdzNFbfzfpyQlMZzh8VC4QMLzAYXNqYPbcLCBVp0.HncNGt
FdxH6VPiQs0nsYUO.J6VXO+GQCQ2vuN5FBVHhkDIOUjxUXYBkqliHJVLmkR3
ILEmR3JlzNXpS+8QUbP.h1r052n3HDElGezfpzinXXQGUCPNYfy2KfImKcQJ
YhQHf4IAnUKFcVWIZnZ.xXpAnJmFf.NGfOBmNIZ.EIkFrAFOEvKgXgm2LO5v
iiSSBEdzzI.dTLaBgGEyUACO0T.O9XX8pzGfc3aPmAs.UDJkNpL5xns4nrAT
2Jr93mGoLhOdjyYb7CDgo7fMjISggTplvyoGxtSmW2rEcac0ZfV0bTaYwRcK
5Sz9g5+lMEqVoqNYB4ioO3io9PIowoLdZJjTMg.LSRS.EBywLgjJGj54118A
edlkd4knLlHtqPE648DAFqHXHUoTf4fZP.JfDYZJlB8YBkP7z5mWTpehlSd4
9hUw8F+eEeaazHRqiDir9vHScG8Ys+rzCCgcGkdcX2wA+MaTElu.Dwf3ucJM
jI66ZTdQSqwS78cqj3bZFxIxefeG58Xk2ewEaQH6P73BxVishoLTYgA1SnEE
FjNqorP2ftcOfb33wBMpMKWOL3mbwvm6okyHtbjDJcP3ewdiotJzvGD9HF93
72tg2P2QVuqZN93xFvGLAJIlVVzZBMYI4R4r5V7.JLAJK6sEhImFR5ti3tKx
A8Ixbjm4RX3WMA0jwDNyLgvlBVeeFQEAyY+RoBcNxd8HzS1ikLL.dQ2Io3Ze
kjcXcbtRxSXLerzyzCQBlcazkC0ffomBmXRpTweQc+pmKaGOj3rh7fiWegvN
urNyDjYVk3iM6BMQXCiA6kkDhxUWyrP8NucbplzjPYa24NX+KzWZq22rT+js
+K4YsF.r61uCwdt2p5CUHlBFosr9P2uSoXwyC3lheHfN4lFc6l5xUPbVned9
yC.+Nn2chGHau1rA8xxG+Pranb9D42ontauRg8YNF662QAmqQxDfMMTVhPwh
AG8jDIzj.0x.MRYBN1xASZa.hJvuA4rg5ZfMEmBSQPRRsMbnLmXTBX.fJKRR
RsKlDS.t+HIPWGFTJgRchQJgDHriRYTNLkTNm.SgfwV9dHacRPdCnUQs6MHK
o6aIjjD6zIThPY2sTtsl6vsZGKVIabSu6yDPfsU5uyrQzUuh3+Bj5nL9Dwpi
vwiNqtADJ4o2uy4g++zPKO+XRibnEN6XGTE7AcPMyXZtfao4imeyJndZhdib
zGyqM0CXHFlSYHR69ycSMGmUma8blye6Q1cquc7Wqg7mK61M8OfN54WKckt0
TT4d4jWLIfbNhbBiPvBJ.43NggvCTRpqljdZUdWYYqbc3hhGDrrY+GAYwCRE
95YU2rR67CHWCg+5I816Z9ocCdP6lda26tYruWp0+XbUD12f775A4HXuY3qk
jruL2URRpqljjAcdUMVhhbtSiigfRtZZuP71Yomxae5ctImHJ2vhqDh9cLNw
HBL69fMiAHmwIiaPYGljDSgIZGgJx6edwyZKa2t6zMsceuSt.C1aqcSWM20s
nx2U351nuqne99QxZ.VjFfB49F+SVcehmjez1ZPvU.AXOvADChzwN197Vs65
dNMGI5a94M+aWnL7.
-----------end_max5_patcher-----------
```

**Comment by tremblap** [comment]
I think it is fixed now, but please confirm

**Comment by tremblap** [comment]
ok you have found a VERY TINY edge case :) to see it work ok, use this patch to add a single silence at the beginning :)

(there is a fix, this is just a teaser)

<pre><code>
----------begin_max5_patcher----------
500.3ocuUEraiBCD8L7UX4yrQ.Ig5rm5+wpUUFxPVGYrQ1l1TU09su1iglzs
rsoQs8.X4wd7yu48X3gzDZs9.XojeR9EII4gzjDLTHPx37DZG+PijawsQUvc
558zr3RN3fCC2JGDaWTOz1n650V3Ix0V8foAHBE45sf0ITbmPqH60pcRvFCZ
cbiq0v6.RwzYJEJnQOnvCtbLnZnSO3jfydZzdtq4OB0taLPiKxhh7UUKxyHE
kkggR1lvvx0KxI+dLq3A4tuGhoPoY9mmWVrEYjmk+nXC8H9B0D7EgXOllFdk
cl0sNvZ46fWU3p4pczYIYwaQxkr.sVwlHmmokuIEmkdrYoW4EPu+isvaHZAy
SAS.p62ufKZoWrlVkiC4r2mvsRM2EDVr.OK6u5KWbaj.2H02kQr7td6QO9Yq
zrhSDZec3RU5puKkd5y6hOrJyJQ1wPodyUeFRb0mlBycNyf3i+g5njsdIpeq
yuT8Km9LHgtkNvbCn30RLq7w0BWRLkW1Z8cKBHhXe2+4WAHiBweYkI1Ye79N
c8HG4zIs6OcSahaZ1p+YiD6aCopy.opWATrVx66uEL1wMiX38S60n7vxvoBU
b5ZbpAtULs+XDtw6lbdqzfAuWzCUqnwT0aAixaGi5nmcdHQupxK21ddjHnkN
8wz+BnEVi+O
-----------end_max5_patcher-----------
</code></pre>

**Comment by rconstanzo** [comment]
Ah nice!

The patch is kind of confusing as to what's happening and/or what's being fixed, but it's good to know that it is a trackable thing.

Does it need to have a single sample of silence for it to start the envelope follower(s) properly? 

I first found this when working with audio recorded in realtime as I couldn't get it to find onsets I knew were there, then just made a test example with jongly, so did get it happening with all sorts of audio.

**Comment by tremblap** [comment]
and it was true for all slicers. now that makes me suspicious so I'll push a PR for @weefuzzy and @AlexHarker to confirm I am right in considering the initial value of not 0 as a bug.

**Comment by tremblap** [comment]
it needs a single silence sample in NRT indeed, to start. I think it is a bug (I'm 99% certain) and I am pushing a fix. I can send 3 binaries for MacOS if you want to roadtest the fix in the meantime

**Comment by rconstanzo** [comment]
Yeah, happy to have a test.

I guess since the other slicers are doing windows, a single sample isn't as critical? As in, `fluid.bufonsetslice~` would find onsets here, just not be as accurate in terms of reporting *where* they are.

**Comment by rconstanzo** [comment]
Testing looks all good here!
