### ISSUE TITLE
Instacrash when `fittransform`-ing in `fluid.umap~`

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-core#277]
I remember this being an issue a while back but it being fixed (hence the `fluid.umap~: Number of Neighbours is larger than dataset` error message now when trying to `fittransform` something that has fewer dimensions than `@numneighbours`) _but_ there appears to have been an oversight when coding it as it gives a nice instacrash when `fittransform`-ing a dataset with the _same_ amount of dimensions as `@numneighbours`.

![Screenshot 2023-07-03 at 11 12 04 AM](https://github.com/flucoma/flucoma-core/assets/2747015/21ed464e-303c-4da6-bae7-91722b907e91)
[patch.zip](https://github.com/flucoma/flucoma-max/files/11935677/patch.zip)

I imagine this means that a `>` needs to get changed to a `>=` when running the size check.

Also including three crash reports, two of which point to a gnarly UMAP error but the third one is different (no flucoma mention at all), so including it in case it's indicative of something else happening at the same time.

[crash reports.zip](https://github.com/flucoma/flucoma-max/files/11935688/crash.reports.zip)

**Comment by tremblap** [comment]
actually this is a duplicate of #278 and there is now a fix.

**Comment by tremblap** [comment]
fix proposed at #279
