### ISSUE TITLE
Crash: `Interpolator` doesn't allocate enough memory at higher SRs

### ISSUE THREAD

**Issue by weefuzzy** [flucoma/flucoma-core#283]
Crash in SC server reported by user here: https://discourse.flucoma.org/t/96khz-seems-to-hangup-the-server/2438

Can reproduce on my mac. Cause turns out to be that at higher sample rates, the buffer for the `Interpolator` used by `Loudness` is undersized, because I clearly wasn't thinking that day. 

The offending line is 

https://github.com/flucoma/flucoma-core/blob/ef77dbafc2735224505a42d05e78c3140827edb4/include/algorithms/util/TruePeak.hpp#L40

which doesn't take into account that for lower upsampling factors for a given number of taps, the max latency would end up being bigger, viz. (49 + 2 -1) / 2 > (49 + 4 - 1) / 4 🤦 

Upshot is that the class doesn't allocate enough storage at 88/96 and so crashes.

**Comment by tremblap** [comment]
This is strange I cannot reproduce the crash. Booting at 96k:

```
b = Buffer.loadCollection(s,96000.collect{|x|(x/480).sin})
b.plot

c = Buffer(s)

FluidBufLoudness.process(s,b,features: c, action: {\done.postln})

c.loadToFloatArray(action: {|x|x.postln})

b.query
```

@weefuzzy how did you reproduce?

**Comment by weefuzzy** [comment]
I batch converted the audio examples folder to 96k and ran the patch that the user posted on discourse

**Comment by tremblap** [comment]
ok the test above crashes in Debug - sorry for the noise
