### ISSUE TITLE
Why do you pad the buffer with the counting numbers in the example?

### ISSUE THREAD

**Issue by robclouth** [flucoma/flucoma-core#30]
https://github.com/flucoma/flucoma-core/blob/19e87109a1048eb48d78a6bc3a01af65d9105333/examples/describe.cpp#L111

Rather than zeros?

**Comment by weefuzzy** [comment]
@g-roma  I'm not sure of the answer to this – do you remember offhand?

**Comment by g-roma** [comment]
Must be some bad copy-paste or typo, surely the author meant something like std::fill, whoever that is

**Comment by jamesb93** [comment]
😮
