### ISSUE TITLE
Initialising MelBands with bands.init(20, 10000, 50, 513, 44100, 1024) fills the mFilters with zeroes

### ISSUE THREAD

**Issue by robclouth** [flucoma/flucoma-core#31]
Am I setting this up correctly? I'm a bit confused about the difference between numBands and windowSize. 
I'm calculating them like this:
```
index numBins = fftSize / 2 + 1;
index hopSize = fftSize / hopRatio;
index windowSize = fftSize;
index halfWindow = windowSize / 2;
```

**Comment by weefuzzy** [comment]
`numBands` is the number of Mel bands to divide the STFT spectrum into, so can be essentially arbitrary up to the limit of the available number of bins. The window size is the number of time domain samples that are used to make an analysis frame, so could be any number <= the fftSize. 

The above looks ok, except that the hopSize should probably be expressed in terms of the window size to cover cases when it != the fftSize. Does that make sense?

**Comment by robclouth** [comment]
Oh sorry, I meant numBins. I'm expressing hop size as a fraction of the window size because that makes more sense from a user perspective in my app.

**Comment by weefuzzy** [comment]
> Oh sorry, I meant numBins. I'm expressing hop size as a fraction of the window size because that makes more sense from a user perspective in my app.

The number of bins for an FFT of real-valued input is going to be half the FFT size plus an extra bin for DC/Nyquist. 

> But why are the filters zero? They are all negative which then gets zeroes with the .max(0).

Ah, sorry, I'd missed that bit of the question. Those arguments look perfectly sensible to me, can you post some code for me to try?

**Comment by robclouth** [comment]
Ah... sorry to waste your time. One of the variables was going out of scope.
