### ISSUE TITLE
Confusing use of rows/columns in fluid.dataset~ print

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-core#39]
When the `print` method is called on a FluidDataSet it uses the words rows/columns to refer to the points and dimensions. We found in the Basel workshop that this is potentially confusing to newcomers, especially when we use the words points / data elsewhere. Rows/columns is very spreadsheet oriented.

<img width="373" alt="image" src="https://user-images.githubusercontent.com/13281862/135750023-aa1ee0c1-d069-4c63-9bdf-86337bdedaa1.png">

I think we can brainstorm a different set of words that will help to glue the concepts of the dataset to the way it is referred to elsewhere.

**Comment by weefuzzy** [comment]
Pretty sure @g-roma  will have valuable input on this. 

People were indeed confused, insofar as it adds to the vocabulary that needs to be learned.  

If we were going for consistency, however, then we'd need to bear in mind that all these data objects also have a `cols` method and `DataSetQuery` uses `cols`.  The json also uses `rows` and `cols`, but specialised internal language feels less problematic there. As such, changing this isn't as simple as just changing the output of `print`.

**Comment by jamesb93** [comment]
> If we were going for consistency, however, then we'd need to bear in mind that all these data objects also have a `cols` method and `DataSetQuery` uses `cols`

Ah okay. Another option is to double down on the spreadsheet metaphor. After all, there is not much interesting about the fact that its some data in a container.

**Comment by g-roma** [comment]
Yes there is rows and cols everywhere. I guess it is hard for me to think you can really understand this without thinking it as a matrix, although I agee it could be more consistent.  Also consider DatasetQuery though, that one does require thinking in rows and columns. 
So maybe the points and dimensions are more of a surface level interface, while rows / cols are more of a peek into the innards, which you get with print.
