### ISSUE TITLE
fluid.bufflatten~ @axis attribute is confusing

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-core#40]
bufflatten~ takes a multichannel buffer and flattens it into a single dimensional buffer.

I'll use the hypothetical two channel, three sample buffer:

1 2 3
> 100 200 300

`@axis 0` is called "Frames" and will transform the input to:

> 1 2 3 100 200 300 

`@axis 1` is called "Channels" and will transform the input to:

> 1 100 2 200 3 300

The naming *feels* backwards for what is done to the input buffer. I think the names should be reversed in this line, keeping the axis value itself the same in order not to break existing patches.

https://github.com/flucoma/flucoma-core/blob/be2255d6a659345490d07b0428cb72ac43108b49/include/clients/nrt/BufFlattenClient.hpp#L35

 [numpy](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html) doesn't offer anything in the way of clearer naming unfortunately 👎 

Maybe `channel-first` or `frame-first`...?

**Comment by weefuzzy** [comment]
New and better documentation solves this
