### ISSUE TITLE
Adding more native audio examples (something percussive/short)

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-core#66]
It's great that there are new audio examples in the files, but having something with percussion/drums would be great.

I suggested the attached ages ag
[Constanzo-PreparedSnare-M.wav.zip](https://github.com/flucoma/flucoma-max/files/7419008/Constanzo-PreparedSnare-M.wav.zip)
o.

**Comment by tremblap** [comment]
@rconstanzo we'll use this to remove some redundant sounds too. That might break many things so we will do it carefully.

**Comment by rconstanzo** [comment]
Only just saw this now. Yeah, having a greater variety of stuff in there would be good.

**Comment by tremblap** [comment]
see PR #135 on core and #184 on Max

**Comment by tremblap** [comment]
closed with PR #135
