### ISSUE TITLE
Read Me instruction for example/describe not working

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-core#70]
Trying to build the examples folder. The instructions say to ```cmake ..``` and that it will 
> download Eigen and the HISSTools library directly at this point.

which it doesn't. I tried ```cmake -DEIGEN_PATH=~/code/eigen -DHISS_PATH=~/code/hisstools_library ..``` but I get at the end of the cmaking:
> Manually-specified variables were not used by the project:
> EIGEN_PATH
> HISS_PATH

In both cases, it doesn't compile:
> /Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/fluid_decomposition/examples/describe.cpp:16:10: fatal error:
>      'AudioFile/IAudioFile.h' file not found
> #include <AudioFile/IAudioFile.h>
>         ^~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.

which I reckon is to be expected. We can fix the read_me or potentially the cmake, I don't know what is best.

if I manually correct all paths to hisstools, to eigen, and even to algo, I still get a lot of moaning about Eigen not being found. Help?

**Comment by weefuzzy** [comment]
If you're configuring `flucoma-core` in a clean build folder then that looks like it should work. Then you should be able to build the describe example: `cmake --build . --target describe` (or `make describe` or `ninja describe` depending on your generator)

**Comment by tremblap** [comment]
ok it is my error: it works if the build folder is not where I would expect it - I sort of read that the build folder was to be made in the example folder but in effect the examples are just more targets at the root level of the full repo. Sorry for the noise.
