### ISSUE TITLE
NoveltySlice w/ MFCCs: Mel frequency range correct? 

### ISSUE THREAD

**Issue by weefuzzy** [flucoma/flucoma-core#86]
@g-roma  

In `NoveltySliceClient`, `mMelBands` is initialized with a frequency range of 20Hz to 2kHz. Is this right, or did you mean 20kHz? 

https://github.com/flucoma/flucoma-core/blob/1e3148e163474c214df6a34cc2063d25cf91b406/include/clients/rt/NoveltySliceClient.hpp#L111-L112

**Comment by g-roma** [comment]
Probably a typo, although generally change in lower frequencies will probably be more interesting. 5k is a common choice for music, and in some cases I have seen  improvements in focusing on environmental sound below 1k, but on top of my head I don't remember having a reason for using 2k here.

**Comment by weefuzzy** [comment]
Cheers for the quick reply. I'd be inclined to change it in that case. Is there stuff that depends on the current behaviour of `NoveltySlice` with MFCCs that's likely to break if / when this happens? (e.g. do your does any of your stuff for FCM2 depend on the current behaviour?)

**Comment by g-roma** [comment]
Certainly not
